measure = 'ddtf';
r = Rs(measure); % chanel/chnnel/freq/PATIENT
nr = NRs(measure);
m = mean(r, 4) - mean(nr, 4);
features = FEATURES(measure);
selected_channels = intersect(intersect(features{1}, features{2}), intersect(features{3}, features{4}));
mean_of_selected_chaanels = m(selected_channels,selected_channels,:);

ddtf1 = permute(mean_of_selected_chaanels(1,:,:), [2 3 1])'; %use ddtf1(:) in plot tool
ddtf2 = permute(mean_of_selected_chaanels(2,:,:), [2 3 1])';
ddtf3 = permute(mean_of_selected_chaanels(3,:,:), [2 3 1])';
ddtf4 = permute(mean_of_selected_chaanels(4,:,:), [2 3 1])';
ddtf5 = permute(mean_of_selected_chaanels(5,:,:), [2 3 1])';
ddtf6 = permute(mean_of_selected_chaanels(6,:,:), [2 3 1])';
ddtf7 = permute(mean_of_selected_chaanels(7,:,:), [2 3 1])';
ddtf8 = permute(mean_of_selected_chaanels(8,:,:), [2 3 1])';
ddtf9 = permute(mean_of_selected_chaanels(9,:,:), [2 3 1])';
ddtf10 = permute(mean_of_selected_chaanels(10,:,:), [2 3 1])';
ddtf11 = permute(mean_of_selected_chaanels(11,:,:), [2 3 1])';
ddtf12 = permute(mean_of_selected_chaanels(12,:,:), [2 3 1])';
ddtf13 = permute(mean_of_selected_chaanels(13,:,:), [2 3 1])';
ddtf14 = permute(mean_of_selected_chaanels(14,:,:), [2 3 1])';
ddtf15 = permute(mean_of_selected_chaanels(15,:,:), [2 3 1])';
ddtf16 = permute(mean_of_selected_chaanels(16,:,:), [2 3 1])';
ddtf17 = permute(mean_of_selected_chaanels(17,:,:), [2 3 1])';
ddtf18 = permute(mean_of_selected_chaanels(18,:,:), [2 3 1])';
ddtf19 = permute(mean_of_selected_chaanels(19,:,:), [2 3 1])';