function C = timeFrequencyAggregation(measure)
	chunk = 1;
	[c1, c2, f, t] = size(measure);
	measure_timeSeg = zeros(c1, c2, f, size(1:20:t, 2));
	for ts = 1:size(measure_timeSeg, 4)
		measure_timeSeg(:,:,:,ts) = median(measure(:,:,:,chunk:chunk+20-1:end), 4);
		chunk = chunk + 20;
	end

	M_TS_M = mean(measure_timeSeg, 4);

	C = cat(...
		3, ...
		mean(M_TS_M(:,:,1:3), 3), ...
		mean(M_TS_M(:,:,4:7), 3), ...
		mean(M_TS_M(:,:,8:13), 3), ...
		mean(M_TS_M(:,:,14:end), 3) ...
	);
end